-- Six more report templates, for the two shapes of company this product has.
--
-- 0077 shipped four starters (blank, lead funnel, sales summary, campaign
-- performance). All three real ones are SCOREBOARDS built from `leads`,
-- `deals`, `contacts` and `campaigns` - they answer "what did we win". Nothing
-- in the library touched `calls`, `tasks` or `invoices`, which means the thing
-- this platform is actually for - the AI read of a recorded phone call - had no
-- report at all, and neither did follow-up discipline or getting paid.
--
-- The gap that matters more, though, is that a tenant running forty telecallers
-- and a tenant running two need different first pages:
--
--   * A CALL FLOOR manages people and conversations. Its questions are who is
--     dialling, whether dialling converts, and who needs coaching - answerable
--     only from `calls` (duration, quality score, talk ratio, interruptions,
--     escalation risk, consent) joined against what those calls produced.
--     Templates 1 and 2.
--   * A SMALL TEAM manages deals and cash. Its questions are what is stuck,
--     where business came from, and who has not paid - `deals`, `campaigns`,
--     `invoices`. Templates 4, 5 and 6.
--   * Template 3 (follow-up) is deliberately for both: on a floor it is "are
--     leads being worked", on a small team it is "is anything falling through".
--
-- Two honesty notes carried in the descriptions rather than discovered later:
-- the quality columns are NULL without the call-intelligence module, and the
-- `leads` and `campaigns` sources cannot be narrowed to a single person
-- (crm-sources.ts: neither has an owner column), so widgets over them refuse an
-- `owned`-scoped persona instead of silently showing them everyone's numbers.
--
-- Every column, aggregation and filter value below was read off crm-sources.ts
-- and the CHECK constraints that define them ('open'/'won'/'lost' on leads and
-- deals, 'open'/'done'/'cancelled' on tasks, 'draft'/'sent'/'paid'/'overdue' on
-- invoices, 'incoming'/'outgoing' and
-- 'not_required'/'played'/'failed'/'pending' on calls). Generated SQL is
-- invisible to typecheck: `node apps/api/verify-report-builder.cjs` executes
-- every widget query here and is the check that these are real.

INSERT INTO report_templates (org_id, key, name, description, category, sort_order, doc, dataset_roles)
VALUES

-- ── 1. the call floor's morning page ────────────────────────────────────────
(NULL, 'telecaller-scorecard', 'Telecaller scorecard',
 'Effort, outcome and call quality per rep on one page - calls made, talk time, what converted, and who is drifting. Quality columns need the call intelligence module. A whole-floor view, so it is for owners and managers.',
 'call-floor', 4,
 '{"version":1,"theme":{"preset":"modern","paletteId":"corporate-navy"},
   "pages":[{"id":"p1","name":"Scorecard","widgets":[
     {"id":"w1","type":"kpi","title":"Calls made","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"agg":"count","alias":"value"}]},
      "options":{"format":"number"}},
     {"id":"w2","type":"kpi","title":"Talk time","layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"duration_s","agg":"sum","alias":"value"}]},
      "options":{"format":"duration"}},
     {"id":"w3","type":"kpi","title":"Average call","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"duration_s","agg":"avg","alias":"value"}]},
      "options":{"format":"duration"}},
     {"id":"w4","type":"kpi","title":"Average quality","subtitle":"Needs call intelligence",
      "layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"quality_score","agg":"avg","alias":"value"}]},
      "options":{"format":"number"}},
     {"id":"w5","type":"chart","chart":"bar","title":"Calls per telecaller",
      "subtitle":"Effort - who is on the phone",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "placeholder":"Map the telecaller column here",
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"agg":"count","alias":"Calls"}],
               "sort":{"key":"Calls","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false,"filterKey":"telecaller_name"}},
     {"id":"w6","type":"chart","chart":"bar","title":"Talk time per telecaller",
      "subtitle":"Seconds on the phone - long calls are not automatically good ones",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"column":"duration_s","agg":"sum","alias":"Seconds"}],
               "sort":{"key":"Seconds","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false,"filterKey":"telecaller_name"}},
     {"id":"w7","type":"table","title":"The scorecard",
      "subtitle":"Effort and quality side by side - the coaching list, worst last",
      "layout":{"x":0,"y":11,"w":12,"h":9},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"agg":"count","alias":"Calls"},
                           {"column":"duration_s","agg":"sum","alias":"Talk seconds"},
                           {"column":"quality_score","agg":"avg","alias":"Avg quality"},
                           {"column":"talk_ratio","agg":"avg","alias":"Talk ratio"},
                           {"agg":"count","alias":"At risk",
                            "where":{"column":"escalation_risk","op":"eq","value":"At risk"}}],
               "derived":[{"alias":"% at risk","op":"pct_of","left":"At risk","right":"Calls"}],
               "sort":{"key":"Calls","direction":"desc"},"limit":50},
      "options":{}},
     {"id":"w8","type":"chart","chart":"line","title":"Calls per day",
      "subtitle":"The floor rhythm - dips are usually staffing, not demand",
      "layout":{"x":0,"y":20,"w":12,"h":7},
      "datasetRole":"calls","respondsToPageFilters":true,
      "placeholder":"Map a date column here for the trend",
      "query":{"dimensions":[{"column":"started_at","bucket":"day"}],
               "measures":[{"agg":"count","alias":"Calls"}],
               "sort":{"key":"started_at","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":false}},
     {"id":"w9","type":"table","title":"What the calling produced",
      "subtitle":"Leads and wins per telecaller - dialling volume means nothing without this",
      "layout":{"x":0,"y":27,"w":12,"h":8},
      "datasetRole":"leads","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"agg":"count","alias":"Leads"},
                           {"agg":"count","alias":"Won",
                            "where":{"column":"status","op":"eq","value":"won"}},
                           {"column":"value_num","agg":"sum","alias":"Won value",
                            "where":{"column":"status","op":"eq","value":"won"}}],
               "derived":[{"alias":"Win rate %","op":"pct_of","left":"Won","right":"Leads"}],
               "sort":{"key":"Leads","direction":"desc"},"limit":50},
      "options":{}}]}]}'::jsonb,
 '[{"role":"calls","label":"Calls","hint":"Recorded calls, one row each","suggestedSourceKey":"calls"},
   {"role":"leads","label":"Leads","hint":"The enquiry stream, to show what the calling produced","suggestedSourceKey":"leads"}]'::jsonb),

-- ── 2. the QA review page ───────────────────────────────────────────────────
(NULL, 'call-quality-review', 'Call quality & compliance',
 'How conversations are actually going - quality scores, how much of the call the rep spent talking, interruptions, and whether the consent notice played. Needs the call intelligence module: without it these read empty rather than wrong.',
 'call-floor', 5,
 '{"version":1,"theme":{"preset":"executive","paletteId":"minimal-mono"},
   "pages":[{"id":"p1","name":"Quality","widgets":[
     {"id":"w1","type":"kpi","title":"Average quality","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"quality_score","agg":"avg","alias":"value"}]},
      "options":{"format":"number"}},
     {"id":"w2","type":"kpi","title":"Average talk ratio","subtitle":"Share of the call the rep spoke",
      "layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"talk_ratio","agg":"avg","alias":"value"}]},
      "options":{"format":"number"}},
     {"id":"w3","type":"kpi","title":"Calls at risk","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"agg":"count","alias":"value",
                            "where":{"column":"escalation_risk","op":"eq","value":"At risk"}}]},
      "options":{"format":"number"}},
     {"id":"w4","type":"kpi","title":"Consent failed","subtitle":"The notice did not play",
      "layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"agg":"count","alias":"value",
                            "where":{"column":"consent_status","op":"eq","value":"failed"}}]},
      "options":{"format":"number"}},
     {"id":"w5","type":"chart","chart":"donut","title":"Consent status",
      "subtitle":"The compliance picture, in one ring",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"consent_status"}],
               "measures":[{"agg":"count","alias":"Calls"}]},
      "options":{"showLegend":true,"filterKey":"consent_status"}},
     {"id":"w6","type":"chart","chart":"donut","title":"Escalation risk",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"escalation_risk"}],
               "measures":[{"agg":"count","alias":"Calls"}]},
      "options":{"showLegend":true,"filterKey":"escalation_risk"}},
     {"id":"w7","type":"chart","chart":"bar","title":"Interruptions per telecaller",
      "subtitle":"Average per call - talking over a customer is the most coachable habit there is",
      "layout":{"x":0,"y":11,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"column":"interruption_count","agg":"avg","alias":"Interruptions"}],
               "sort":{"key":"Interruptions","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false,"filterKey":"telecaller_name"}},
     {"id":"w8","type":"chart","chart":"bar","title":"Longest monologue",
      "subtitle":"Average longest unbroken stretch, in seconds",
      "layout":{"x":6,"y":11,"w":6,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"column":"longest_monologue_seconds","agg":"avg","alias":"Seconds"}],
               "sort":{"key":"Seconds","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false}},
     {"id":"w9","type":"chart","chart":"line","title":"Is coaching working?",
      "subtitle":"Average quality score by week",
      "layout":{"x":0,"y":19,"w":12,"h":7},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"started_at","bucket":"week"}],
               "measures":[{"column":"quality_score","agg":"avg","alias":"Avg quality"}],
               "sort":{"key":"started_at","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":false}},
     {"id":"w10","type":"table","title":"Who to listen to first",
      "subtitle":"Lowest average quality at the top",
      "layout":{"x":0,"y":26,"w":12,"h":8},
      "datasetRole":"calls","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"telecaller_name"}],
               "measures":[{"column":"quality_score","agg":"avg","alias":"Avg quality"},
                           {"column":"talk_ratio","agg":"avg","alias":"Talk ratio"},
                           {"column":"interruption_count","agg":"avg","alias":"Interruptions"},
                           {"agg":"count","alias":"Calls"}],
               "sort":{"key":"Avg quality","direction":"asc"},"limit":25},
      "options":{}}]}]}'::jsonb,
 '[{"role":"calls","label":"Calls","hint":"Recorded calls with their AI quality read","suggestedSourceKey":"calls"}]'::jsonb),

-- ── 3. the one both shapes of company need ──────────────────────────────────
(NULL, 'follow-up-discipline', 'Follow-up discipline',
 'What is overdue, who owes it, and which leads have gone quiet. On a call floor this is "are leads being worked"; on a small team it is "is anything falling through the cracks".',
 'pipeline', 6,
 '{"version":1,"theme":{"preset":"minimal","paletteId":"vibrant-sunset"},
   "pages":[{"id":"p1","name":"Follow-up","widgets":[
     {"id":"w1","type":"kpi","title":"Open tasks","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"agg":"count","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}]},
      "options":{"format":"number"}},
     {"id":"w2","type":"kpi","title":"Overdue","layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"agg":"count","alias":"value",
                            "where":{"column":"overdue","op":"eq","value":"Overdue"}}]},
      "options":{"format":"number"}},
     {"id":"w3","type":"kpi","title":"Share overdue","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"agg":"count","alias":"total"},
                           {"agg":"count","alias":"late",
                            "where":{"column":"overdue","op":"eq","value":"Overdue"}}],
               "derived":[{"alias":"value","op":"div","left":"late","right":"total"}]},
      "options":{"format":"percent"}},
     {"id":"w4","type":"kpi","title":"Leads open 14+ days","layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"leads","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"agg":"count","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"open"},
                          {"column":"age_days","op":"gte","value":14}]},
      "options":{"format":"number"}},
     {"id":"w5","type":"chart","chart":"bar","title":"Overdue by assignee",
      "subtitle":"Who is underwater - the escalation list",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"assignee_name"}],
               "measures":[{"agg":"count","alias":"Overdue",
                            "where":{"column":"overdue","op":"eq","value":"Overdue"}}],
               "sort":{"key":"Overdue","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false,"filterKey":"assignee_name"}},
     {"id":"w6","type":"chart","chart":"donut","title":"Open work by priority",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"priority"}],
               "measures":[{"agg":"count","alias":"Tasks"}],
               "filters":[{"column":"status","op":"eq","value":"open"}]},
      "options":{"showLegend":true,"filterKey":"priority"}},
     {"id":"w7","type":"chart","chart":"line","title":"Work cleared per week",
      "subtitle":"Completed follow-ups - is the team keeping up with intake?",
      "layout":{"x":0,"y":11,"w":12,"h":7},
      "datasetRole":"tasks","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"completed_at","bucket":"week"}],
               "measures":[{"agg":"count","alias":"Completed"}],
               "filters":[{"column":"completed_at","op":"not_null"}],
               "sort":{"key":"completed_at","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":false}},
     {"id":"w8","type":"table","title":"Gone quiet",
      "subtitle":"Open leads, oldest first. This is the page''s point - work these today",
      "layout":{"x":0,"y":18,"w":12,"h":8},
      "datasetRole":"leads","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"title"},{"column":"stage"},{"column":"telecaller_name"}],
               "measures":[{"column":"age_days","agg":"max","alias":"Days open"},
                           {"column":"value_num","agg":"max","alias":"Value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}],
               "sort":{"key":"Days open","direction":"desc"},"limit":25},
      "options":{}}]}]}'::jsonb,
 '[{"role":"tasks","label":"Tasks","hint":"Follow-up work with an assignee and a due date","suggestedSourceKey":"tasks"},
   {"role":"leads","label":"Leads","hint":"The enquiry stream, for the ones going quiet","suggestedSourceKey":"leads"}]'::jsonb),

-- ── 4. the pipeline review ──────────────────────────────────────────────────
(NULL, 'pipeline-health', 'Pipeline health',
 'Where deals are stuck, what is forecast to close, and which ones nobody has phoned. The counterpart to Sales summary: that page is what you won, this one is what is quietly going wrong.',
 'pipeline', 7,
 '{"version":1,"theme":{"preset":"executive","paletteId":"forest-emerald"},
   "pages":[{"id":"p1","name":"Health","widgets":[
     {"id":"w1","type":"kpi","title":"Open pipeline","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"amount","agg":"sum","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}]},
      "options":{"format":"currency"}},
     {"id":"w2","type":"kpi","title":"Open deals","layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"agg":"count","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}]},
      "options":{"format":"number"}},
     {"id":"w3","type":"kpi","title":"Avg days in stage","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"days_in_stage","agg":"avg","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}]},
      "options":{"format":"number"}},
     {"id":"w4","type":"kpi","title":"Win rate","layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"agg":"count","alias":"total"},
                           {"agg":"count","alias":"won",
                            "where":{"column":"status","op":"eq","value":"won"}}],
               "derived":[{"alias":"value","op":"div","left":"won","right":"total"}]},
      "options":{"format":"percent"}},
     {"id":"w5","type":"chart","chart":"bar","title":"Where deals get stuck",
      "subtitle":"Average days sitting in each stage",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"stage"}],
               "measures":[{"column":"days_in_stage","agg":"avg","alias":"Avg days"}],
               "filters":[{"column":"status","op":"eq","value":"open"}],
               "sort":{"key":"Avg days","direction":"desc"}},
      "options":{"showLegend":false,"filterKey":"stage"}},
     {"id":"w6","type":"chart","chart":"bar","title":"Open value by stage",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"stage"}],
               "measures":[{"column":"amount","agg":"sum","alias":"Value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}],
               "sort":{"key":"Value","direction":"desc"}},
      "options":{"showLegend":false,"filterKey":"stage"}},
     {"id":"w7","type":"chart","chart":"bar","title":"Expected to close",
      "subtitle":"Open value by the month it is forecast to land",
      "layout":{"x":0,"y":11,"w":12,"h":7},
      "datasetRole":"deals","respondsToPageFilters":true,
      "placeholder":"Map the expected close date here",
      "query":{"dimensions":[{"column":"expected_close_date","bucket":"month"}],
               "measures":[{"column":"amount","agg":"sum","alias":"Value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}],
               "sort":{"key":"expected_close_date","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":false}},
     {"id":"w8","type":"table","title":"Stalled deals",
      "subtitle":"Longest in their current stage - the agenda for a pipeline review",
      "layout":{"x":0,"y":18,"w":12,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"name"},{"column":"stage"},{"column":"owner_name"}],
               "measures":[{"column":"days_in_stage","agg":"max","alias":"Days in stage"},
                           {"column":"amount","agg":"max","alias":"Value"}],
               "filters":[{"column":"status","op":"eq","value":"open"}],
               "sort":{"key":"Days in stage","direction":"desc"},"limit":25},
      "options":{}},
     {"id":"w9","type":"table","title":"Never phoned",
      "subtitle":"Open deals with no call logged against them at all",
      "layout":{"x":0,"y":26,"w":12,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"name"},{"column":"stage"},{"column":"owner_name"}],
               "measures":[{"column":"amount","agg":"max","alias":"Value"}],
               "filters":[{"column":"status","op":"eq","value":"open"},
                          {"column":"call_count","op":"eq","value":0}],
               "sort":{"key":"Value","direction":"desc"},"limit":25},
      "options":{}}]}]}'::jsonb,
 '[{"role":"deals","label":"Deals","hint":"One row per deal, with its stage and value","suggestedSourceKey":"deals"}]'::jsonb),

-- ── 5. attribution, measured in money ───────────────────────────────────────
(NULL, 'revenue-attribution', 'Where business comes from',
 'Channels and campaigns measured in revenue rather than lead count - including how much won value has no source attached at all, which is usually the most useful number on the page.',
 'marketing', 8,
 '{"version":1,"theme":{"preset":"modern","paletteId":"vibrant-sunset"},
   "pages":[{"id":"p1","name":"Attribution","widgets":[
     {"id":"w1","type":"kpi","title":"Won value","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"amount","agg":"sum","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"won"}]},
      "options":{"format":"currency"}},
     {"id":"w2","type":"kpi","title":"Unattributed","subtitle":"Won value with no source",
      "layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"amount","agg":"sum","alias":"value"}],
               "filters":[{"column":"status","op":"eq","value":"won"},
                          {"column":"source_channel","op":"eq","value":"Unattributed"}]},
      "options":{"format":"currency"}},
     {"id":"w3","type":"kpi","title":"Campaign spend","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"campaigns","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"spend","agg":"sum","alias":"value"}]},
      "options":{"format":"currency"}},
     {"id":"w4","type":"kpi","title":"Return on spend","subtitle":"Won value per unit spent",
      "layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"campaigns","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"column":"won_value","agg":"sum","alias":"won"},
                           {"column":"spend","agg":"sum","alias":"spend"}],
               "derived":[{"alias":"value","op":"div","left":"won","right":"spend"}]},
      "options":{"format":"number"}},
     {"id":"w5","type":"chart","chart":"bar","title":"Won value by channel",
      "subtitle":"Which channels actually produce revenue",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"source_channel"}],
               "measures":[{"column":"amount","agg":"sum","alias":"Won value"}],
               "filters":[{"column":"status","op":"eq","value":"won"}],
               "sort":{"key":"Won value","direction":"desc"}},
      "options":{"showLegend":false,"filterKey":"source_channel"}},
     {"id":"w6","type":"chart","chart":"bar","title":"Win rate by channel",
      "subtitle":"Volume and quality are different questions - this is the second one",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"source_channel"}],
               "measures":[{"agg":"count","alias":"Deals"},
                           {"agg":"count","alias":"Won",
                            "where":{"column":"status","op":"eq","value":"won"}}],
               "derived":[{"alias":"Win rate %","op":"pct_of","left":"Won","right":"Deals"}],
               "sort":{"key":"Win rate %","direction":"desc"},
               "topN":{"enabled":true,"n":10}},
      "options":{"showLegend":true}},
     {"id":"w7","type":"chart","chart":"area","title":"Won value by month",
      "layout":{"x":0,"y":11,"w":12,"h":7},
      "datasetRole":"deals","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"created_at","bucket":"month"}],
               "measures":[{"column":"amount","agg":"sum","alias":"Won value"}],
               "filters":[{"column":"status","op":"eq","value":"won"}],
               "sort":{"key":"created_at","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":false}},
     {"id":"w8","type":"table","title":"Campaign returns",
      "subtitle":"Spend against what it produced. Cost per lead is correct at every grouping here",
      "layout":{"x":0,"y":18,"w":12,"h":8},
      "datasetRole":"campaigns","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"name"},{"column":"channel"}],
               "measures":[{"column":"spend","agg":"sum","alias":"Spend"},
                           {"column":"lead_count","agg":"sum","alias":"Leads"},
                           {"column":"deal_count","agg":"sum","alias":"Deals"},
                           {"column":"won_value","agg":"sum","alias":"Won value"}],
               "derived":[{"alias":"Cost per lead","op":"div","left":"Spend","right":"Leads"},
                          {"alias":"Return","op":"div","left":"Won value","right":"Spend"}],
               "sort":{"key":"Won value","direction":"desc"},"limit":25},
      "options":{}}]}]}'::jsonb,
 '[{"role":"deals","label":"Deals","hint":"Deals carry the revenue and the channel that produced them","suggestedSourceKey":"deals"},
   {"role":"campaigns","label":"Campaigns","hint":"One row per marketing source, with its spend","suggestedSourceKey":"campaigns"}]'::jsonb),

-- ── 6. getting paid ─────────────────────────────────────────────────────────
(NULL, 'cash-collections', 'Cash & collections',
 'Billed, collected and still owed, with the oldest unpaid invoices at the top of the chase list. For whoever has to ring people about money.',
 'finance', 9,
 '{"version":1,"theme":{"preset":"minimal","paletteId":"corporate-navy"},
   "pages":[{"id":"p1","name":"Collections","widgets":[
     {"id":"w1","type":"kpi","title":"Billed","layout":{"x":0,"y":0,"w":3,"h":3},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"total","agg":"sum","alias":"value"}]},
      "options":{"format":"currency"}},
     {"id":"w2","type":"kpi","title":"Collected","layout":{"x":3,"y":0,"w":3,"h":3},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"amount_paid","agg":"sum","alias":"value"}]},
      "options":{"format":"currency"}},
     {"id":"w3","type":"kpi","title":"Outstanding","layout":{"x":6,"y":0,"w":3,"h":3},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[],"measures":[{"column":"outstanding","agg":"sum","alias":"value"}]},
      "options":{"format":"currency"}},
     {"id":"w4","type":"kpi","title":"Overdue","layout":{"x":9,"y":0,"w":3,"h":3},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[],
               "measures":[{"column":"outstanding","agg":"sum","alias":"value",
                            "where":{"column":"status","op":"eq","value":"overdue"}}]},
      "options":{"format":"currency"}},
     {"id":"w5","type":"chart","chart":"bar","title":"Owed by account",
      "subtitle":"The chase list, biggest first",
      "layout":{"x":0,"y":3,"w":6,"h":8},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"account_name"}],
               "measures":[{"column":"outstanding","agg":"sum","alias":"Outstanding"}],
               "sort":{"key":"Outstanding","direction":"desc"},
               "topN":{"enabled":true,"n":15}},
      "options":{"showLegend":false,"filterKey":"account_name"}},
     {"id":"w6","type":"chart","chart":"donut","title":"Invoices by status",
      "layout":{"x":6,"y":3,"w":6,"h":8},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"status"}],
               "measures":[{"agg":"count","alias":"Invoices"}]},
      "options":{"showLegend":true,"filterKey":"status"}},
     {"id":"w7","type":"chart","chart":"line","title":"Billed against collected",
      "subtitle":"By month - a widening gap is a collections problem, not a sales one",
      "layout":{"x":0,"y":11,"w":12,"h":7},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"created_at","bucket":"month"}],
               "measures":[{"column":"total","agg":"sum","alias":"Billed"},
                           {"column":"amount_paid","agg":"sum","alias":"Collected"}],
               "sort":{"key":"created_at","direction":"asc"}},
      "options":{"showGrid":true,"showLegend":true}},
     {"id":"w8","type":"table","title":"Chase list",
      "subtitle":"Anything still owed, oldest due date first",
      "layout":{"x":0,"y":18,"w":12,"h":8},
      "datasetRole":"invoices","respondsToPageFilters":true,
      "query":{"dimensions":[{"column":"invoice_number"},{"column":"account_name"},
                             {"column":"status"},{"column":"due_date"}],
               "measures":[{"column":"outstanding","agg":"max","alias":"Outstanding"}],
               "filters":[{"column":"outstanding","op":"gt","value":0}],
               "sort":{"key":"due_date","direction":"asc"},"limit":25},
      "options":{}}]}]}'::jsonb,
 '[{"role":"invoices","label":"Invoices","hint":"What was billed, paid and is still outstanding","suggestedSourceKey":"invoices"}]'::jsonb)

ON CONFLICT DO NOTHING;
