package com.voicetranscriber.callrecorder.platform

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.CipherInputStream
import javax.crypto.CipherOutputStream
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * At-rest encryption for recordings (platform claim: "encrypted on device and in
 * storage, decrypted only inside the pipeline"). A single AES-256-GCM key lives in
 * the Android Keystore — the raw key bytes never leave hardware.
 *
 * On-disk layout of an encrypted file: [12-byte random IV][GCM ciphertext+tag].
 * The IV is generated by the Keystore provider per-encryption (Keystore refuses a
 * caller-supplied IV for GCM encryption), read back via [Cipher.getIV], and
 * prepended so decryption can recover it.
 */
object FileCrypto {

    private const val ALIAS = "aura_file_key"
    private const val STORE = "AndroidKeyStore"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val IV_BYTES = 12
    private const val TAG_BITS = 128

    private fun keyStore(): KeyStore = KeyStore.getInstance(STORE).apply { load(null) }

    /** Fetches the Keystore AES-256 key, generating it on first use. */
    private fun secretKey(): SecretKey {
        val store = keyStore()
        (store.getEntry(ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, STORE)
        generator.init(
            KeyGenParameterSpec.Builder(
                ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                // Recording/upload run unattended; requiring user auth would break them.
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return generator.generateKey()
    }

    /** Encrypts [plain] into [enc] (IV prepended). [enc] is overwritten if present. */
    fun encryptFile(plain: File, enc: File) {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, secretKey())
        val iv = cipher.iv // 12 bytes, provider-generated
        enc.outputStream().buffered().use { out ->
            out.write(iv)
            CipherOutputStream(out, cipher).use { cipherOut ->
                plain.inputStream().buffered().use { it.copyTo(cipherOut) }
            }
        }
    }

    /**
     * Decrypts [enc] to a fresh temp file (created alongside it) and returns it.
     * Caller owns the temp file and must delete it once consumed.
     */
    fun decryptToTemp(enc: File): File {
        val temp = File.createTempFile("aura_dec_", ".m4a", enc.parentFile)
        enc.inputStream().buffered().use { input ->
            val iv = ByteArray(IV_BYTES)
            var read = 0
            while (read < IV_BYTES) {
                val n = input.read(iv, read, IV_BYTES - read)
                require(n >= 0) { "encrypted file too short for IV" }
                read += n
            }
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secretKey(), GCMParameterSpec(TAG_BITS, iv))
            CipherInputStream(input, cipher).use { cipherIn ->
                temp.outputStream().buffered().use { cipherIn.copyTo(it) }
            }
        }
        return temp
    }
}
